name: Create a bump pr

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Version
        required: true
        default: minor
        type: choice
        options:
          - major
          - minor
          - patch
# bump/version-name => main
jobs:
  create_bump_pr:
    runs-on: ubuntu-latest
    env:
      LEVEL: ${{ inputs.logLevel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # https://github.com/orgs/community/discussions/26560#discussioncomment-3252339
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Create bump pr
        run: |
          NEXT_VERSION=`npm version $LEVEL --no-commit-hooks --no-git-tag-version`
          git flow release start $NEXT_VERSION
          npm version $LEVEL --no-git-tag-version # update package.json
          git push -u origin HEAD && gh pr create -t "Bump to $NEXT_VERSION to stg" -b "" -l bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}