name: Release

on:
  workflow_dispatch:

jobs:
  incremental_tag_and_release_build:
    if: startsWith(github.head_ref, 'release/') && github.event.pull_request.merged == true
    permissions:
      contents: write # for release-drafter/release-drafter to create a github release
      pull-requests: write # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - name: Publish a release // for staging
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          prerelease: true
          publish: true
          tag: $LATEST_TAG